# Generated by Django 5.0.4 on 2024-04-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordCounterApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessInquiry',
        ),
    ]
